name: Custom badges

on:
  push:
    branches:
      - main

jobs:
  badge-job:
    name: Generate some custom badges for README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: db_count
        run: |
          echo "##[set-output name=data;]$(grep -e 'name:' lgtm_db/data/db.yaml | wc -l)"

      - name: DB Count badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: count
          LABEL: "GIF count"
          STATUS: ${{ steps.db_count.outputs.data }}
          COLOR: purple
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
