name: Validate pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  validate:
    name: Various checks for the pull request
    runs-on: ubuntu-latest

    steps:
      - name: PR title naming rules
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            refactor
            chore
            docs
            ci
            perf
            release
          requireScope: false
          # subject must not begin with an uppercase letter, and must be at least
          # be 10 characters long
          subjectPattern: ^(?![A-Z]).{10,}$
