name: Validate pull request

on:
  - pull_request

jobs:
  validate:
    name: Various checks for the pull request
    runs-on: ubuntu-latest

    steps:
      - name: PR title naming rules
        uses: naveenk1223/action-pr-title@v1.0.0
        with:
          regex: '([a-z])+: \w+'
          allowed_prefixes: 'fix,feat,refactor,chore,docs,ci,perf,release'
          prefix_case_sensitive: true
          min_length: 10
