name: Tests

on: [push]

jobs:
  validate-gallery-html:
    name: Checks if the gallery html file is up-to-date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Setup python dependencies
        run: pip install ".[dev]"

      - name: Run the comparison of gallery files
        run: |
          mv docs/index.html docs/index-old.html
          python -m scripts.generate_gallery
          diff docs/index.html docs/index-old.html
